include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Báo lỗi biến/hàm không dùng
    unused_local_variable: true
    unused_element: true
    unused_field: true
    unused_import: true

    # Code style
    prefer_const_constructors: true
    prefer_final_fields: true
    use_key_in_widget_constructors: true
    avoid_print: false # Nhắc nhở dùng logger thay vì print