include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore

linter:
  rules:
    # Báo lỗi biến/hàm không dùng
    unnecessary_import: true
    unused_local_variable: true
    unused_catch_stack: true
    avoid_unused_constructor_parameters: true
    # Code style
    prefer_const_constructors: true
    prefer_final_fields: true
    use_key_in_widget_constructors: true
    avoid_print: false